package hw.happyjacket.com.familycontactlist.extention;
/**
 * Created by root on 16-3-27.
 */

/*Accessory is used to refine the elements generated by cursor*/
public interface Accessory {

     String decorate(String key,String value);

}
